### ISSUE TITLE
Missing cable trace when multi termination cables.

### ISSUE THREAD

**Issue by joaolucasmacedo** [netbox-community/netbox#10602]
### NetBox version

v3.3.2

### Python version

3.10

### Steps to Reproduce

0. Create a regular fiber patch panel device with 24 front and rear ports (12 pairs).
1. Create a cable connecting more than 2 rear ports between devices, like 2 fiber patch panels connected by a 2 or 3 pair fiber cable. 
2. Connect 2 devices by its interfaces using the correspondent front ports from each patch panel.
3. See that the trace does not "see" the 2 ending interfaces relationship.

### Expected Behavior

Being able to see each device on each connection end.
My goal is to model 2 devices connected by 2 fiber patch panels.
Each patch panel has 12 double SC ports(24 rear and front ports with 1 position).
Patch panels are connected by a 3 pair fiber cable on 6 rear ports each.
Device interfaces are connected using patch panel's front ports on each side.

Router1-Gig0/0/3 >> |frontPort <> Patch panel <> rearPort| <>----3 pair fiber cable----<>|rearPort <> Patch panel <> frontPort| << Gig0/0/3-Router2

### Observed Behavior

It only works as expected if I make each connection using 2 terminations on the middle cable, as if it was a single pair cable between patch panels. 
See the Cable 25 on the images bellow.
![Cabele trace1](https://user-images.githubusercontent.com/66760118/194569656-a4f83774-4c7a-43a3-9478-942d83e94581.png)
If the cable between patch panels is connected to a pair of rear ports on each side everything works fine and I can see the peering device as below:
![Link peer2](https://user-images.githubusercontent.com/66760118/194570109-162d9272-f313-4f53-a4b5-878f6e608ea9.png)

But if I connect 3 pairs of rear ports on each side of cable 25, as it is on real world, is lost the reace between devices:
![Cabele trace2](https://user-images.githubusercontent.com/66760118/194570432-59731490-e4f7-453d-978e-04871384ea57.png)

![Link peer3](https://user-images.githubusercontent.com/66760118/194570471-b15498c6-9ed2-4c7c-896e-01a66c17ee02.png)

**Comment by jeremystretch** [comment]
I'm not sure this specific topology is something we're able to support. Typically, you would model this as multiple front ports mapped to a single rear port, rather than multiple rear ports all terminated to a common cable. The root challenge is that there's no strict ordering of the individual cable terminations, so it's not feasible to reliably determine the proper far-end terminations when tracing the cable path.

**Comment by hhcatv** [comment]
It is a real situation that high-fiber-count cables are spliced ​​into multiple ODF trays.
Suppose I link 2 network optical distribution frames [ODF] with 24-core optical cable, and each ODF contains 2 ODF trays, which is the real situation.
The tray is constructed in a modular way to facilitate the automatic naming of ports. The tray module creates 12 front ports and 1 rear port (required in netbox), the rear port corresponds to the 12 cores in the fiber optic cable.
Insert the tray module into the 2 slots of the ODF, and connect the 2 back ports to the 2 back ports of another ODF, that is, to the same optical cable. At this time, the cable routing will appear abnormal.
【Google Translate】
ODF1 front ports:
![image](https://user-images.githubusercontent.com/131244255/234739271-352c8862-b04d-41f9-b6a2-d0337ec35f24.png)

ODF1 rear ports:
![image](https://user-images.githubusercontent.com/131244255/234739232-32c9378f-f72c-4b73-a660-94ec1b4903c3.png)

ODF front ports2:
![image](https://user-images.githubusercontent.com/131244255/234739320-56ed3faf-aefa-4604-b87f-30cf0a22e696.png)

ODF2 rear ports:
![image](https://user-images.githubusercontent.com/131244255/234739369-f35b1cc8-06a8-4d75-8e25-37f5338fca4f.png)

Cable Trace:
![image](https://user-images.githubusercontent.com/131244255/234739543-bba80520-0972-4d81-ab9c-8e612a9423e0.png)

**I don't know, maybe I didn't find the right solution, forgive my translated text.**

**Comment by DanSheps** [comment]
I believe this is fixed with #11079 as it is a similar problem

**Comment by h3po** [comment]
I am facing the same problem when modeling split switch interfaces. I have 4 split switch interfaces connected through a single MPO cable into a module that maps 1 rear to 4 front ports, so the cable is terminated 4x on one side into the single rear port. Attaching an interface to one of the front ports results in that interface being traced to all 4 switch ports.

**Comment by arthanson** [comment]
@h3po @joaolucasmacedo Can you please try this on NetBox 4?  We think this might have possibly been resolved via #13337

**Comment by h3po** [comment]
@arthanson I just tested with 2faa72c1e921 (v4.0.3), the behavior is still the same.
In this example, the "test" interface shows as connected to all 4 switch ports
![image](https://github.com/netbox-community/netbox/assets/8227075/4742825c-cdfc-4785-8c40-e59b6c1dd0d4)

**Comment by joaolucasmacedo** [comment]
> @h3po @joaolucasmacedo Can you please try this on NetBox 4? We think this might have possibly been resolved via #13337

Hi @h3po I'll try it soon.

**Comment by joaolucasmacedo** [comment]
> > @h3po @joaolucasmacedo Can you please try this on NetBox 4? We think this might have possibly been resolved via #13337
> 
> Hi @h3po I'll try it soon.

Hi. I've just tested with NetBox 4.0.5(demo) and it is the same.
Also there is some other bugs I found trying to model some fiber patch/splices.

**Comment by DanSheps** [comment]
Could you supply the full path in the form of a graph of some kind for both of your scenarios?  This is likely an unsupported path but we could possible add support for it, via a FR

**Comment by joaolucasmacedo** [comment]
> Could you supply the full path in the form of a graph of some kind for both of your scenarios? This is likely an unsupported path but we could possible add support for it, via a FR

Please, see #16571 
Or [see this tace](https://demo.netbox.dev/dcim/interfaces/928/trace/)

**Comment by DanSheps** [comment]
I want to see what it should look like, not what it looks like currently

**Comment by joaolucasmacedo** [comment]
> I want to see what it should look like, not what it looks like currently

It should look loke [this](https://demo.netbox.dev/dcim/interfaces/912/trace/):

![image](https://github.com/netbox-community/netbox/assets/66760118/b9c6ec25-59e5-4731-b3f6-6f1777fb7002)

As I show on #16571 I'm trying to model a connection between 2 switches that passes through 2 fiber patch panels, and may use different cables connected on its rear ports.

**Comment by DanSheps** [comment]
So, it looks like it works in your example (because I see it on the demo site), but I think I know what is going on here:

When it enters DIO X1 on the FP1 a cable position is pushed to a position stack.  It **normally** shouldn't matter what order it is pushed in as most enter and exit the same cable on the rear port side, however when it is pushed because there are two different cables, the rear port matters, because when it is popped off the stack, it we need to order the cables in reverse order, otherwise, what we can have is:

```
[FP1-1A][RP1] --- [RP1][FP1-5A]
[FP2-5A][RP2] --- [RP2][FP2-1A]
```

As you can see, the position is flipped.

I think there might be some overlap with #11671 as implementing #11671 would allow us to potentially get rid of the position stack.

I have marked #16571 as a duplicate of this, as it really is all related I believe, and closed it out.

**Comment by derjam** [comment]
It looks like this issue is very identical to my reported bug. [#17400](https://github.com/netbox-community/netbox/issues/17400)
I reported a very simple example to reproduce it.

**Comment by jeremystretch** [comment]
This appears to work as expected on NetBox v4.1.7 (see below), so I'm going to close this. For any related issues, please submit a **new** bug report with reproduction steps for the current stable release.

![screenshot](https://github.com/user-attachments/assets/20195d90-04f0-4290-b946-f37701cbe938)
