### ISSUE TITLE
Error on non-regex search for invalid regex string

### ISSUE THREAD

**Issue by sleepinggenius2** [netbox-community/netbox#11516]
### NetBox version

v3.4.2

### Python version

3.8

### Steps to Reproduce

1. Create a *Site* with Name = *"Foo (Bar)"* and Slug = *"foo-bar"*
2. Perform a default global search or explicit *Partial match* search for the string *"(Bar"*
3. Receive error

### Expected Behavior

The *Site* should have been found and the string appropriately highlighted in the result. I believe this is caused by the use of `re.split` in `utilities.utils.highlight_string`, as I could not find where the highlight string is being escaped for non-regex searches.

### Observed Behavior

The following error is received:

```
<class 're.error'>

missing ), unterminated subpattern at position 0

Python version: 3.8.10
NetBox version: 3.4.2
```

**Comment by kkthxbye-code** [comment]
@sleepinggenius2 - Good catch, I just totally forgot regex seach was added. Do you want to test your proposal and submit a PR?

**Comment by sleepinggenius2** [comment]
I can try, but it will take me a bit to get a development environment set back up again for 3.4. I'm also not quite sure how to go about formal testing, as I don't see where there are currently test cases defined for the search functionality and my knowledge of Python and Django is not at a level where I would even know how to begin to do that from scratch. I can tell you that changing that line (and adding `import re` to the file) on our server makes the error go away and seems to allow it to highlight properly for all the lookup types.

**Comment by jeremystretch** [comment]
I think I've fixed this in 591104177. Thanks for the catch.

**Comment by opericgithub** [comment]
I still receive the same error. I have device named "(9)123" (without quotes). When searching for "(9" without quotes in global search I get the error, but when searching for "(9)" I get regular search results.

**Comment by sleepinggenius2** [comment]
Yeah, I don't see where the non-regex path was actually impacted. I think this:

https://github.com/netbox-community/netbox/blob/97723b1f96735de2c95d92af58a9292b7a69affd/netbox/netbox/views/misc.py#L171

should have been this:

```python
highlight = re.escape(form.cleaned_data['q'])
```

or the escaping from #11525 should have been kept here:

https://github.com/netbox-community/netbox/blob/97723b1f96735de2c95d92af58a9292b7a69affd/netbox/utilities/utils.py#L530

**Comment by jeremystretch** [comment]
Whoops. In introducing a new logic path for regex searches I seem to have lost the escape function.

**Comment by jeremystretch** [comment]
I've opened #11555 for this.
