### ISSUE TITLE
allow decimals for rack type dimensions

### ISSUE THREAD

**Issue by rconkor** [netbox-community/netbox#20941]
### NetBox version

v.4.4.7

### Feature type

Change to existing functionality

### Proposed functionality

please allow decimals for rack type dimensions.

### Use case

Take for example the APC AR3105B2 rack.
https://www.se.com/us/en/product/AR3105B2/apc-netshelter-sx-server-rack-gen-2-45u-2124h-x-600w-x-1070d-mm-with-sides-black-taa/

According to the product datasheet, the dimensions for the rack are as follows:
Height: 83.6 inches (2124mm)
Width: 23.6 inches (600mm)
Depth: 42.1 inches (1070mm)

Currently, unless you want to use millimeters exclusively (which we don't), there is not a way to model these exact dimensions. When inputting decimals in the "outer dimensions" for rack types, we are met with a field validation error.

Found : https://github.com/netbox-community/netbox/issues/17510
Jeremy mentions this would be a breaking change. I think 4.5 is coming up soon, maybe this would be a good candidate?

### Database changes

possibly need to change fields from INTEGER to DECIMAL. 

### External dependencies

none

**Comment by jnovinger** [comment]
Looks to be a duplicate of #17510, which was closed as stale just last year.

**Comment by arthanson** [comment]
You can put the dimensions in millimeters.  This should solve the issue.

**Comment by rconkor** [comment]
@arthanson that doesn't solve the issue. Please re-open and evaluate the request to actually allow NetBox to reflect reality. Many manufacturers do not publish dimensions in metric.
