### ISSUE TITLE
Interface.DoesNotExist error when deleting a device with active connections

### ISSUE THREAD

**Issue by dgarros** [netbox-community/netbox#3559]
### Environment
* Python version:  3.6.8
* NetBox version:  2.6.5

When deleting a device that has one or multiple connections to other devices, netbox is returning an `dcim.models.Interface.DoesNotExist` error. 
If I disconnect all interfaces prior to deleting the device, the error is not present.

```
<class 'dcim.models.Interface.DoesNotExist'>

Interface matching query does not exist
```
### Steps to Reproduce
1. Create 2 devices (dev1 and dev2)
2. Connect 2 interfaces together from dev1 and dev2
3. Delete dev1

### Expected Behavior
Device should be deleted without issue and all connections to this device should be deleted as well

### Observed Behavior
Netbox is returning a `dcim.models.Interface.DoesNotExist` error

```
<class 'dcim.models.Interface.DoesNotExist'>
Interface matching query does not exist
```

**Comment by kobayashi** [comment]
How can I reproduce this? when I try, delete operation works fine to me with the same netbox version.
Can you let me know the step in detail like parameters to reproduce?

**Comment by dgarros** [comment]
Here is the full trace, hope this help 
```
Request Method: | POST
-- | --
http://<server_address>/dcim/devices/delete/?q=&region=demo-build-network&mac_address=&has_primary_ip=&local_context_data=&virtual_chassis_member=&console_ports=&console_server_ports=&power_ports=&power_outlets=&interfaces=&pass_through_ports=&cf_dev_pb_vlan_management=
2.2.5
DoesNotExist
Interface matching query does not exist.
/usr/local/lib/python3.6/site-packages/django/db/models/query.py in get, line 408
/usr/bin/python3.6
3.6.8
['/opt/netbox/netbox',  '/usr/local/bin',  '/usr/lib64/python36.zip',  '/usr/lib64/python3.6',  '/usr/lib64/python3.6/lib-dynload',  '/usr/local/lib64/python3.6/site-packages',  '/usr/local/lib/python3.6/site-packages',  '/usr/local/lib/python3.6/site-packages/pip-19.2.3-py3.6.egg',  '/usr/local/lib/python3.6/site-packages/gunicorn-19.9.0-py3.6.egg',  '/usr/lib64/python3.6/site-packages',  '/usr/lib/python3.6/site-packages']
Mon, 7 Oct 2019 21:04:18 +0000
```

```
Traceback:

File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py" in __get__
  164.             rel_obj = self.field.get_cached_value(instance)

File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/mixins.py" in get_cached_value
  13.             return instance._state.fields_cache[cache_name]

During handling of the above exception ('_connected_interface'), another exception occurred:

File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/opt/netbox/netbox/extras/middleware.py" in __call__
  112.             enqueue_webhooks(obj, request.user, request.id, objectchange.action)

File "/opt/netbox/netbox/extras/webhooks.py" in enqueue_webhooks
  47.                 serializer.data,

File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py" in data
  563.         ret = super(Serializer, self).data

File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py" in data
  262.                 self._data = self.to_representation(self.instance)

File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py" in to_representation
  530.                 ret[field.field_name] = field.to_representation(attribute)

File "/usr/local/lib/python3.6/site-packages/rest_framework/fields.py" in to_representation
  1889.         return method(value)

File "/opt/netbox/netbox/dcim/api/serializers.py" in get_connected_endpoint_type
  34.         if hasattr(obj, 'connected_endpoint') and obj.connected_endpoint is not None:

File "/opt/netbox/netbox/dcim/models.py" in connected_endpoint
  2369.         if self._connected_interface:

File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py" in __get__
  178.                 rel_obj = self.get_object(instance)

File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py" in get_object
  298.         return super().get_object(instance)

File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py" in get_object
  145.         return qs.get(self.field.get_reverse_related_filter(instance))

File "/usr/local/lib/python3.6/site-packages/cacheops/query.py" in get
  356.         return qs._no_monkey.get(qs, *args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py" in get
  408.                 self.model._meta.object_name

Exception Type: DoesNotExist at /dcim/devices/delete/
Exception Value: Interface matching query does not exist.
```

**Comment by DanSheps** [comment]
This could possibly be a caching issue, however:

I was unable to reproduce this following the exact steps on https://master.netbox.dansheps.com

Please provide reproducible steps.

**Comment by lampwins** [comment]
From the traceback, we can see that this is related to webhooks. To reproduce it, you will need to have to a webhook enabled.

**Comment by kobayashi** [comment]
I tried to again with webhook enabled environment. The delete operation with interfaces works and my worker received all delete events through webhook.
Here is my steps
- create device1
- create device2
- create interfaces1 and interface2 in both devices
- connect interface1,2 in device1 to interface1,2 in deviece2
- delete device1

I might need add some data to somewhere to reproduce.

Please let me know your step in detail. @dgarros 

The tested environment:
- Python version: 3.7.4
- NetBox version: 2.6.5

**Comment by DanSheps** [comment]
Can you give us your webhook configuration as well @dgarros

**Comment by dgarros** [comment]
The issue is present when we have a webhook for dcim>interface configured with Create/Update/Delete
I tried to disable the webhook and the issue is not present anymore

Right now the webhook endpoint is down, not sure if that makes a difference or not

**Comment by kobayashi** [comment]
I was trying with webhook configured as follow
- object types: dcim.device, dcim.interface
- set only type delete

**Comment by jeremystretch** [comment]
@dgarros Can you try testing this against the `3309-changelog-middleware` branch? I have a feeling this might have been fixed inadvertently.

**Comment by jeremystretch** [comment]
Marking this as blocked pending testing of the changes to the middleware merged in #3632

**Comment by dgarros** [comment]
@jeremystretch I tested the latest code in `develop` and the issue is still present for me.
I can provide a setup where the problem is present if that can help

**Comment by jeremystretch** [comment]
@dgarros All reported bugs need to be reproducible in a stock release. If you can determine the exact scenario which triggers the bug, please update the "steps to reproduce" above so that others can try as well.
