### ISSUE TITLE
Can't model a break out panel connecting two devices

### ISSUE THREAD

**Issue by mngan** [netbox-community/netbox#4819]
### Environment
* Python version: 3.6.9
* NetBox version: 2.8.6

### Steps to Reproduce
1. Create a panel with 1 MPO rear port breaking out out to 4 LC front ports
2. Create a device with a 40G QSFP+ interface
3. Create a device with a 10G SFP+ interface
4. Connect 10G interface to LC front port
5. Connect 40G interface to MPO rear port

### Expected Behavior
On the last step, I would expect you to be able to connect the 40G interface to the MPO rear port

### Observed Behavior
Instead, Netbox says `Rear ports with multiple positions may only be connected to other rear ports`

What I am trying to do is model a panel that allows me to break out 40/100G MPO ports to 10/25G LC ports. It seems the only way to achieve this is to add in a dummy panel that has MPO front ports and MPO rear ports. 

```
10G Device --- LC/MPO Panel === 40G Device
```

**Comment by mngan** [comment]
I guess another way to solve this is to build the LC and MPO ports as front ports, then create pairs of MPO ports on the rear side that can be patched together. One member of the pair maps to the LC ports and the other maps to the MPO port.

**Comment by jsenecal** [comment]
I may be wrong but I believe this has been fixed in https://github.com/netbox-community/netbox/pull/4706

**Comment by mngan** [comment]
#4706 doesn't fix this unfortunately. It still only lets passthrough ports connect to a rear port, and not interfaces. 

["Rear ports with multiple positions may only be connected to other pass-through ports"](https://github.com/netbox-community/netbox/blob/56ec4a6360772c5a404d34bedb4b767787267454/netbox/dcim/models/__init__.py#L2204
)

**Comment by jeremystretch** [comment]
@steffann can you look into this please? Seems related to #4706

**Comment by steffann** [comment]
NetBox currently doesn't support splitting QSFP ports into SFP ports. Neither breakout cables nor breakout patch panels are supported. This would be nice to have, but it would require that interfaces can have sub-interfaces that are treated as separate interfaces while sharing a single connection. This is currently not possible.

You can work around this by creating 4 separate interfaces (the sub-interfaces), creating a rear port that will be the QSFP and creating 4 fake front ports to connect to the sub-interfaces. So you'll end up with:

```
+------------------------------------+
|             Device                 |
|                                    |
| +------------+    +-----+          |
| | xe-0/0/0:0 +----+ FP0 +-----+    |
| +------------+    +-----+     |    |
|                               |    |
| +------------+    +-----+     |    |
| | xe-0/0/0:1 +----+ FP1 +---+ |    |
| +------------+    +-----+  +--+----+-+
|                            | QSFP RP +--------+
| +------------+    +-----+  +--+----+-+
| | xe-0/0/0:2 +----+ FP2 +---+ |    |
| +------------+    +-----+     |    |
|                               |    |
| +------------+    +-----+     |    |
| | xe-0/0/0:3 +----+ FP3 +-----+    |
| +------------+    +-----+          |
|                                    |
+------------------------------------+
```

I realise that this is a hack, but it is currently the best work-around that I can come up with.

**Comment by steffann** [comment]
The other work-around is of course to model the QSFP link from the interface to the breakout panel as 4 cables. An MPO cable actually contains 4 fiber pairs, and you could create them separately. In that case your breakout panel would be modeled with 4 rear ports (MPO fiber pair 1, MPO fiber pair 2, etc) with each one front port.

**Comment by steffann** [comment]
I have discussed this with the maintainer team, and we don't have the capacity to change the database models and code to implement this at this time. I will mark this as a potential idea that might be reconsidered in the future (no promises!) and close it for now.
