### ISSUE TITLE
Allow exclude object permission in 2.9

### ISSUE THREAD

**Issue by a31amit** [netbox-community/netbox#4949]
### Environment
* Python version:  3.8
* NetBox version:  2.9-beta-1

### Proposed Functionality
To Allow exclude() method on object permission along with filter()

### Use Case
This change would allow us to protect information related to pre-released hardware where group belongs to tenant A can see everything else however very specific users for tenants would also able to see pre-released hardware information added to netbox specially Device Inventory tab. 
At present with object permission, users can filter information but cannot use exclude()

Example - 
Assume you have 20-40 items in inventory tab such as cpu/ ram/ disk / gpu and so on. if we wanted to exclude only 1 or 2 inventory items, we have to create filters for all to display so remaining items not included in filter() don't show up. 

That means users will end up creating filter for each inventory item. but if Django query exclude() support with netbox, than we can just add what to exclude but remaining would show up. 

We record some Pre-Released hardware information netbox inventory tab. this is a very important feature where we can allow users to see most of the inventory items but very specific people can query or see pre-released hw info 

### Database Changes
Not sure 

### External Dependencies
Should be none as Object Permission is core feature of netbox

**Comment by lampwins** [comment]
@jeremystretch will need to comment on the viability of this. My opinion would be to not do this as it basically equates to access controls based on a blacklist, which can be very dangerous if not properly understood. I would want to push this in the direction of using a `pre-release` tag on inventory items which would require us to support tags there as a separate issue.

**Comment by lampwins** [comment]
Clarification, we do actually support tags on inventory items, just not on the creation form, which is really a bug.

**Comment by lampwins** [comment]
And is already fixed in 2.9. I'm new here :)

**Comment by a31amit** [comment]
I am still not sure if without exclude or control based on a blacklist such cases even possible. but I believe blacklist or exclude would be having same impact as filter. when you do blacklist, you know exactly what you blacklisted, with filters it's even more concerned because there would be a lot of permission with filter OR statement which can easily be missed out.

**Comment by jeremystretch** [comment]
> when you do blacklist, you know exactly what you blacklisted

You know exactly what you've blacklisted, but not what you've _neglected_ to blacklist. This is @lampwins' point: It's much easier to audit what access has been specifically allowed, as opposed to ensuring everything that shouldn't be allowed has been blocked. A blacklist-based approach fails in an non-secure fashion, as opposed to a whitelist which denies access by default.

That said, I can see a use case for the inversion. It could be as simple as implementing an "invert" checkbox on the ObjectPermission model which, when applied, calls `exclude()` with the prescribed constraints rather than `include()`. We'd just need to make it _very_ clear to the user that the length of rope he or she is being issued is more than enough to hang oneself.

**Comment by jeremystretch** [comment]
I've looked into this a bit further, but I'm a little stuck at how we'd efficiently convey the negation of constraints when caching assigned permissions on the user instance. The current approach results in a dictionary similar to the following:

```
{
    'ipam.view_vlan': [
        {'vid__gte': 100, 'vid__lt': 200},
        {'status': 'reserved'}
    ],
    'dcim.view_site': [
        {'name__startswith': 'foo'}
    ],
    'dcim.view_region': [None]
}
```

In this example, the user can view VLANs and sites with some constraints, and can view _all_ regions.

I like this arrangement because we can check for the existence of a specific permission as a dictionary key to quickly determine whether the user has that permission on at least _some_ objects (if the user did not, the key would not exist). This is handy for things like disabling navigation menu items.

To support negation for permission constraints, we'll need to come up with an elegant way to convey the inversion when caching permissions, ideally while maintaining the current dictionary-based approach.

**Comment by a31amit** [comment]
@jeremystretch  - Can we Please exclude this from auto-remove stale bot. I still believe this feature would be very useful and wish to get implemented in core. lately noticing that auto stale-bot seems closing many outstanding issues.

**Comment by jeremystretch** [comment]
@a31amit sorry, but it doesn't look like there's been any further interest in it from the community, and the development effort it would demand honestly isn't going to be worthwhile.

**Comment by hballiance** [comment]
+1

This would be useful for us. For example I want to restrict access for a group of users. Allow them access to all devices that contain "aaa" in name however exclude ones that also contain "bbb" in name. The following should happen...

- Device: "aaa-ccc-123" > Allow
- Device "aaa-bbb-123" > Deny
