### ISSUE TITLE
When editing a device interface "Parent" and "LAG" choices are not scoped to current device

### ISSUE THREAD

**Issue by maznu** [netbox-community/netbox#6857]
### NetBox version

v3.0-beta1

### Python version

3.7

### Steps to Reproduce

1. Edit a device interface.
2. Click on the "Parent Interface" or "LAG Interface" drop-down.
3. Oh no, it's every single device-interface (up to MAX_PAGE_SIZE).

### Expected Behavior

Parent should only allow interfaces on the current device.

### Observed Behavior

Drop-downs fetch `/api/dcim/interfaces/?brief=true&limit=0` and `/api/dcim/interfaces/?brief=true&limit=0&type_id=virtual` with no filter.

**Comment by thatmattlove** [comment]
This was reported in #6797 and should have been fixed in 5413263, see [here](https://github.com/netbox-community/netbox/issues/6797#issuecomment-889729361). Can you pull the latest changes from the `feature` branch and test again, please?

**Comment by jeremystretch** [comment]
Can confirm this has already been resolved in `feature`.

**Comment by maznu** [comment]
I think there's sort of still an issue, but it's a bit more subtle now.

If I'm on a high latency link (3G, VPN, etc) then what I notice happening is this:

1. go to make a cable connection from a device interface to another device interface
2. drop down the list of devices for the right hand side
3. select my device
4. API query returns with a couple of interfaces
5. …and then the earlier API query which had all the interfaces ever returns, and the interface drop-down is unhelpful

Here's a video to explain better: https://fs.maz.nu/netbox-api-concurrency-dfBBU8lPyNPPbxBC.mov

You'll just catch "eth0" at the top of the interface list for a moment, before it looks like the earlier query returns with everything.
