### ISSUE TITLE
VLAN site mappings is broken in the UI

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox#7174]
### NetBox version

v3.0.1

### Python version

3.9

### Steps to Reproduce

- View VLAN object GUI page shows site mapped to VLAN https://demo.netbox.dev/ipam/vlans/1/
- Edit VLAN object GUI page show the tab to assign a site, but does not show a site drop down. https://demo.netbox.dev/ipam/vlans/1/edit/
- The same issue when adding new VLANs

### Expected Behavior

Be able to add & update site assignments for a VLAN.

### Observed Behavior

This impacts VLANs but not VLAN Groups

**Comment by ryanmerolle** [comment]
I just realized this should have been fixed by #7131

**Comment by DanSheps** [comment]
We don't have 3.0.2 yet, so it isn't in master yet.  We can re-open if not resolved.
